"""add fields period & last_renewed

Revision ID: 1a03011574c6
Revises: b45b809bce81
Create Date: 2025-04-05 15:19:39.794249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a03011574c6'
down_revision: Union[str, None] = 'b45b809bce81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limits', sa.Column('period', sa.String(), nullable=True))
    op.add_column('limits', sa.Column('last_renewed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('limits', 'last_renewed')
    op.drop_column('limits', 'period')
    # ### end Alembic commands ###
